### DISCUSSION TITLE
Write error: Unable to write data to the transport connection

### DISCUSSION THREAD

**Discussion by DuvelCorp** [slskd/slskd#1007] [General]
Hi

I share a large lib, users can find my files (unsure if they can browse), but I am unable to upload files because of this error happening all the time whenever an upload transfer is initiated.

![image](https://github.com/slskd/slskd/assets/33682764/f517eb41-14f9-4079-8bee-cd0a463960ce)

Note that it might be a VPN issue. Everything is running on docker and slskd runs on a container in a shared network with gluetun that handles the VPN connection (wireguard protocol) and the WAN. 
My VPN is probably fine. Other containers like Prowlarr are using it without any issues.

Here's the idea:

```
version: "3"
services:
# ----------- -------- GLUETUN - VPN --------------------------
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 9696:9696  # Prowlarr     
      # - 7878:7878  # Radarr
      - 5030:5030  # slskd http
      - 5031:5031  # slskd https
      - 8191:8191  # flaresolverr
    volumes:
      - /media/seedbox/.config/gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=xxxxxx
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=xxxxx
      - WIREGUARD_ADDRESSES=10.14.0.2/16
      - SERVER_COUNTRIES=Netherlands
      - TZ=Europe/Brussels
      - FIREWALL=on
      - FIREWALL_OUTBOUND_SUBNETS=192.168.0.0/16 
      - FIREWALL_VPN_INPUT_PORTS=38080
      - HTTPPROXY=on
      - HTTPPROXY_LOG=on
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=on
# ----------------- PROWLARR - Indexers ---------------------
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    depends_on:
      - gluetun  
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Brussels
    volumes:
      - /media/seedbox/.config/Prowlarr:/config
    #ports:
    #  - 9696:9696
    restart: unless-stopped
 

# ----------------------- SOULSEEK -------------------------------
  slskd:
    container_name: slskd
    image: slskd/slskd:latest
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - TZ=Europe/Brussels
      - SLSKD_SLSK_USERNAME=xxxxx
      - SLSKD_SLSK_PASSWORD=xxxxx
      - SLSKD_INCOMPLETE_DIR=/downloads/incomplete
      - SLSKD_DOWNLOADS_DIR=/downloads/complete
      - SLSKD_SHARED_DIR=/musique
    user: 1001:1001
    volumes:
      - /media/seedbox/slskdownloads:/downloads
      - /media/seedbox/.config/soulseek:/data
      - /nfs/media/musique:/musique
```

I might have something to tweak somewhere in slskd but I don't know what. I googled for this  error and searched here and can't find anything relevant

Important note: I can download without any issue.

Help

Cheers
