### DISCUSSION TITLE
Unable to use Relay mode when using docker tailscale and slskd

### DISCUSSION THREAD

**Discussion by p0lygun** [slskd/slskd#1138] [Q&A]
Hi there, ive been trying to get the relay mode to get working on a tailscale network but the `agent` refuses to connect to the `controller`

on my VPS. controller is hosted with the compose

```yml
services:
  ts-soulseek-controller:
    image: tailscale/tailscale:latest
    container_name: ts-soulseek-controller
    hostname: soulseek-controller
    environment:
      - TS_AUTHKEY=tskey-client-REDACTED?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:soulseek
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/soulseek.json        
    volumes:
      - ${PWD}/ts-soulseek-controller/state:/var/lib/tailscale
      - ${PWD}/ts-soulseek-controller/config:/config        
      - /dev/net/tun:/dev/net/tun
    ports:
      - 50300:50300/tcp
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  slskd-controller:
    environment:
      - SLSKD_SLSK_ADDRESS=server.slsknet.org
      - SLSKD_SLSK_PORT=2242
    volumes:
      - /root/softwares/slskd:/app:rw
    image: slskd/slskd:latest
    network_mode: service:ts-soulseek-controller
    depends_on:
      - ts-soulseek-controller
volumes:
  ts-soulseek-controller:
    driver: local
  slskd-controller:
    driver: local

```

slskd.yml

```yml
instance_name: controller
relay:
  enabled: true
  mode: controller
  agents:
    gala_home_pc:
      instance_name: gala_home_pc 
      secret: REDACTED
      cidr: 100.81.124.51/32
web:
  authentication:
    api_keys:
      gala_home_pc_api_key: 
        key: REDACTED
        role: readwrite
        cidr: 100.81.124.51/32 
  ```

on my local machine slskd is hosted in agent mode in docker again 
```yml
version: "3"
services:
  ts-soulseek-agent:
    image: tailscale/tailscale:latest
    container_name: ts-soulseek-agent
    hostname: soulseek-agent
    environment:
      - TS_AUTHKEY=tskey-client-REDACTED?ephemeral=false
      - TS_EXTRA_ARGS=--advertise-tags=tag:soulseek
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/soulseek_agent.json        
    volumes:
      - ${PWD}/ts-soulseek-agent/state:/var/lib/tailscale
      - ${PWD}/ts-soulseek-agent/config:/config        
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped


  slskd-agent:

    volumes:
      - /home/gala/softwares/slskd:/app:rw
      - /media/chunky/sync/music:/music:rw
    network_mode: service:ts-soulseek-agent
    depends_on:
      - ts-soulseek-agent      
    image: slskd/slskd:latest

volumes:
  ts-soulseek-agent:
    driver: local
  slskd-agent:
    driver: local

```

` slskd.local.config`  

```yml

instance_name: gala_home_pc
relay:
  enabled: true
  mode: agent
  controller:
    address: https://soulseek-controller.tail2ca7b.ts.net:5031/
    ignore_certificate_errors: true 
    api_key: REDACTED
    secret: REDACTED
    downloads: true
shares:
  directories:
    -/media/chunky/sync/music 
```

logs on local
```
d-agent-1  | [09:33:51 INF] Attempting to connect to the relay controller https://soulseek-controller.tail2ca7b.ts.net:5031
slskd-agent-1  | [09:33:51 INF] Version 0.21.0.0 is up to date.
slskd-agent-1  | [09:33:53 WRN] Failed attempt #1 to connect to relay controller: Response status code does not indicate success: 401 (Unauthorized).
slskd-agent-1  | [09:33:53 INF] Attempting to connect to the relay controller https://soulseek-controller.tail2ca7b.ts.net:5031
slskd-agent-1  | [09:33:54 WRN] Failed attempt #2 to connect to relay controller: Response status code does not indicate success: 401 (Unauthorized).
slskd-agent-1  | [09:33:55 INF] Attempting to connect to the relay controller https://soulseek-controller.tail2ca7b.ts.net:5031
slskd-agent-1  | [09:33:56 WRN] Failed attempt #3 to connect to relay controller: Response status code does not indicate success: 401 (Unauthorized).
^CGracefully stopping... (press Ctrl+C again to force)
[+] Stopping 1/1
```

whats weird is i can access the webUI at https://soulseek-controller.tail2ca7b.ts.net:5031 so i know that tailscale is working. but i cant access it in the container.

![image](https://github.com/slskd/slskd/assets/22869882/168b89d8-527d-4db0-9fdd-85767fc0f873)
