### DISCUSSION TITLE
Downloads files one by one

### DISCUSSION THREAD

**Discussion by F0ofoon** [slskd/slskd#1317] [Q&A]
Hi, first of all thanks a lot for the work in this project, very usefull !

I am noticing that when downloading a folder, it downloads the files one by one but when I was using SoulseekQt I think it did download multiple files at once.
Am I missing something in the config ?

<details>
<summary>Config</summary>

```yml
# debug: false
# headless: false
remote_configuration: true
# remote_file_management: false
# instance_name: default
# flags:
#   no_logo: false
#   no_start: false
#   no_config_watch: false
#   no_connect: false
#   no_share_scan: false
#   force_share_scan: false
#   no_version_check: false
#   log_sql: false
#   experimental: false
#   volatile: false
#   case_sensitive_reg_ex: false
#   legacy_windows_tcp_keepalive: false
#   optimistic_relay_file_info: false
# relay:
#   enabled: false
#   mode: controller # controller (default), agent, or debug (for local development)
#   # controller config is required when running in 'agent' mode
#   # this specifies the relay controller that will be controlling this agent
#   controller:
#     address: https://some.site.com:5000
#     ignore_certificate_errors: false
#     api_key: <a 16-255 character string corresponding to one of the controller's 'readwrite' or 'administrator' API keys>
#     secret: <a 16-255 character shared secret matching the controller's config for this agent>
#     downloads: false
#   # agent config is optional when running in 'controller' mode
#   # this specifies all of the agents capable of connecting
#   agents:
#     my_agent:
#       instance_name: my_agent # make sure the top-level instance_name of the agent matches!
#       secret: <a 16-255 character string unique to this agent>
#       cidr: 0.0.0.0/0,::/0
# permissions:
#   file:
#     mode: ~ # not for Windows, chmod syntax, e.g. 644, 777. can't escalate beyond umask
directories:
  incomplete: /soulseek/incomplete
  downloads: /soulseek/downloads
shares:
  directories:
    - /music
#   filters:
#     - \.ini$
#     - Thumbs.db$
#     - \.DS_Store$
#   cache:
#     storage_mode: memory
#     workers: 16
#     retention: ~ # retain indefinitely (do not automatically re-scan)
# rooms:
#   - ~
global:
  upload:
    slots: 20
    speed_limit: 10240 # in kibibytes
#   limits:
#     queued:
#       files: 500
#       megabytes: 5000
#     daily:
#       files: 1000
#       megabytes: 10000
#       failures: 200
#     weekly:
#       files: 5000
#       megabytes: 50000
#       failures: 1000
#   download:
#     slots: 500
#     speed_limit: 1000
# groups:
#   default:
#     upload:
#       priority: 500
#       strategy: roundrobin
#       slots: 10
#     limits:
#       queued:
#         files: 150
#         megabytes: 1500
#       daily: ~ # no daily limits (weekly still apply)
#       weekly:
#         files: 1500
#         megabytes: 15000
#         failures: 150
#   leechers:
#     thresholds:
#       files: 1
#       directories: 1
#     upload:
#       priority: 999
#       strategy: roundrobin
#       slots: 1
#       speed_limit: 100
#     limits:
#       queued:
#         files: 15
#         megabytes: 150
#       daily:
#         files: 30
#         megabytes: 300
#         failures: 10
#       weekly:
#         files: 150
#         megabytes: 1500
#         failures: 30
#   blacklisted:
#     members:
#       - <username to blacklist>
#     cidrs:
#       - <CIDR to blacklist, e.g. 255.255.255.255/32>
#   user_defined:
#     my_buddies:
#       upload:
#         priority: 250
#         strategy: firstinfirstout
#         slots: 10
#       limits:
#         queued:
#           files: 1000 # override global default
#       members:
#         - alice
#         - bob
# blacklist:
#   enabled: true
#   file: <path to file containing CIDRs to blacklist>
# filters:
#   search:
#     request:
#       - ^.{1,2}$
web:
  port: 5030
  https:
    disabled: false
    port: 5031
    force: false
    certificate:
      pfx: ~
      password: ~
  url_base: /
  content_path: wwwroot
  logging: false
  authentication:
    disabled: true
    username: slskd
    password: slskd
#    jwt:
#      key: ~
#      ttl: 604800000
#    api_keys:
#      my_api_key:
#        key: <some example string between 16 and 255 characters>
#        role: readonly # readonly, readwrite, administrator
#        cidr: 0.0.0.0/0,::/0
# retention:
#   searches: 10080 # 7 days, in minutes
#   transfers:
#     upload:
#       succeeded: 1440 # 1 day, in minutes
#       errored: 30
#       cancelled: 5
#     download:
#       succeeded: 1440 # 1 day, in minutes
#       errored: 20160 # 2 weeks, in minutes
#       cancelled: 5
#   files:
#     complete: 20160 # 2 weeks, in minutes
#     incomplete: 43200 # 30 days, in minutes
#   logs: 180 # days
# logger:
#   disk: false
#   no_color: false
#   loki: ~
# metrics:
#   enabled: false
#   url: /metrics
#   authentication:
#     disabled: false
#     username: slskd
#     password: slskd
# feature:
#   swagger: false
soulseek:
  address: vps.slsknet.org
  port: 2271
  username: Fxxxxxxx
  password: xxxxxxxxxxxxx
#   description: |
#     A slskd user. https://github.com/slskd/slskd
#   listen_ip_address: 0.0.0.0
#   listen_port: 50300
#   diagnostic_level: Info
#   distributed_network:
#     disabled: false
#     disable_children: false
#     child_limit: 25
#     logging: false
#   connection:
#     timeout:
#       connect: 10000
#       inactivity: 15000
#     buffer:
#       read: 16384
#       write: 16384
#       transfer: 262144
#       write_queue: 250
#     proxy:
#       enabled: false
#       address: ~
#       port: ~
#       username: ~
#       password: ~
# integration:
#   webhooks:
#     my_webhook:
#       on:
#         - DownloadFileComplete
#       call:
#         url: https://192.168.1.42:8080/slskd_webhook
#         headers:
#           - name: X-API-Key
#             value: foobar1234
#           - name: Authorization
#             value: Bearer eyJ...ssw5c
#           - name: User-Agent
#             value: slskd/0.0
#         ignore_certificate_errors: false
#       timeout: 5000 # in milliseconds
#       retry:
#         attempts: 3
#   scripts:
#     my_post_download_script:
#       on:
#         - DownloadFileComplete
#         - DownloadDirectoryComplete
#       run: data/my_script.sh --json-to-process $EVENT
#     my_logging_script:
#       on:
#        - All
#       run: data/log_slskd_events.sh $DATA
#   ftp:
#     enabled: false
#     address: ~
#     port: ~
#     username: ~
#     password: ~
#     remote_path: /
#     encryption_mode: auto
#     ignore_certificate_errors: false
#     overwrite_existing: true
#     connection_timeout: 5000
#     retry_attempts: 3
#   pushbullet:
#     enabled: false
#     access_token: ~
#     notification_prefix: "From slskd:"
#     notify_on_private_message: true
#     notify_on_room_mention: true
#     retry_attempts: 3
#     cooldown_time: 900000

```

</details>
