### DISCUSSION TITLE
Can’t make work run command when file is downloaded on Mac OS

### DISCUSSION THREAD

**Discussion by Badsheep** [slskd/slskd#1349] [Q&A] [answered]
Hello !

I can’t make work a command when a file is downloaded (I use slskd on Mac OS)…

Does anybody achieves this on Mac OS ?
Thanks !

**Comment by Badsheep** [comment]
Here's a a part of my yml file : 

```
 integration:
  scripts:
    my_post_download_script:
      on:
        - DownloadFileComplete
        - DownloadDirectoryComplete
#      run: /bin/sh data/my_script.sh --json-to-process "$DATA" # Linux/macOS
#      run: /bin/sh /Users/badsheep/Documents/CONFIGURATION\ iMAC\ IMAGE\ ET\ SON\ MATTHIEU/Soulseek/whenfilefinished.sh #--json-to-process "$DATA" # Linux/macOS
      run: /bin/sh open -n /Applications/Cantata.app #--json-to-process "$DATA" # Linux/macOS
```
and the error message in the terminal : 

badsheep@MacInfame scripts % [13:31:01 WRN] Failed to run script 'mypostdownloadscript' for event type DownloadDirectoryComplete: STDERR: zsh: error on TTY read: Input/output error  Saving session... ...copying shared history... ...saving history...truncating history files... ...completed.  (id: 2cbf2053-446e-4d90-b39c-00a9aa3dc343)
[13:31:01 WRN] Failed to run script 'mypostdownloadscript' for event type DownloadFileComplete: STDERR: zsh: error on TTY read: Input/output error  Saving session... ...saving history...rm: /Users/badsheep/.zsh_sessions/3B64671F-0812-40C1-80E8-56B8CB2BBCBE.historynew: No such file or directory truncating history files... ...completed.  (id: 7fd119b7-934b-4622-8141-125807aa8c2a)

**Comment by Badsheep** [comment, marked as answer]
I made it !
If anyone is interested, here's my working yml : 

```
 integration:
  scripts:
    my_post_download_script:
      on:
        - DownloadFileComplete
        - DownloadDirectoryComplete
      run:
        command: '/Users/badsheep/.slskd/whenfilefinished.sh'
```
