### DISCUSSION TITLE
Change web server port

### DISCUSSION THREAD

**Discussion by Kristoffeh** [slskd/slskd#1351] [Q&A] [answered]
Hello!

I started using this project on docker via an image on dockerhub, but have decided to move away from docker and use linux containers instead.

I'm using the [slskd-0.22.5-linux-x64.zip](https://github.com/slskd/slskd/releases/download/0.22.5/slskd-0.22.5-linux-x64.zip) package from releases page.

I've set the most necessary settings in the `config/slskd.yml` to make it functional. I'd like to make the URL a bit cleaner by using port `80`, so i set the appropriate values for the `web` section of the yml.

Is this an incomplete feature? Or is this setting for something else? No matter what i do, the port is always port `5030`.
As you can see below, the authentication is also disabled but it is not disabled when i visit `http://192.168.113.22:5030/`

I'd love to just get some pointers as to what i am doing wrong.

Web section:
```
 web:
   port: 80
     https:
       disabled: true
     port: 5031
     force: false
     certificate:
       pfx: ~
       password: ~
   url_base: /
   content_path: wwwroot
   logging: false
   authentication:
     disabled: true
     username: slskd
     password: slskd
```
