### DISCUSSION TITLE
Missing yaml config in repository and config clarifications

### DISCUSSION THREAD

**Discussion by tandy-1000** [slskd/slskd#153] [Q&A] [answered]
The default yaml config doesn't seem to be anywhere in the repo anymore?
It was packaged in the latest release (there is no indication on how to use multiple shared directories with the config file so I was looking for it to find some clues).

Also, I was wondering whether there would be any benefit to making a Matrix chat for this project? I suppose as there is only one maintainer for now there wouldn't be much yet..

**Comment by jpdillingham** [comment]
The default config that gets copied over to the release is here: https://github.com/slskd/slskd/blob/master/src/slskd/Properties/slskd.yml

I see what you're saying about the example, I'll see about updating it to include a few commented out entries.  I intend to write some actual documentation now that the configuration stuff has stopped changing so frequently.

It crossed my mind to create a chat, I'll think about the best place.

**Reply by BachoSeven** [reply]
By the way, the URL to the `.yml` config file in the README should be updated to the one you linked

**Reply by tandy-1000** [reply]
That makes sense, it might be worth making a wiki page, I'd be happy to contribute to that.
I strongly suggest Matrix due to its bridging capabilities, bridges exist for services like Gitter, Discord and Telegram.

**Comment by jpdillingham** [comment, marked as answer]
Circling back on this, quite a bit has changed since it was posted!

A full example of the config is now located [here](https://github.com/slskd/slskd/blob/master/config/slskd.example.yml), and this is copied to the application directory when the application starts if no config file is found.

The configuration is now documented [here](https://github.com/slskd/slskd/blob/master/docs/config.md), with some other typical configurations covered [in this directory](https://github.com/slskd/slskd/tree/master/docs) (docker, reverse proxies, etc)

An official chat for slskd has been established on [Discord](https://slskd.org/discord) with a relay to [Matrix](https://slskd.org/matrix).

**Comment by saveriogzz** [comment]
Hey 👋  I'm exhuming this thread instead of opening a new one, hope that's ok!
I'm having some troubles in making the app to start up (Mac Silicon, Docker).

I'm using a the following command
```bash
docker run \
  -p 5030:5030 \
  -p 5031:5031 \
  -p 50300:50300 \
  -e SLSKD_REMOTE_CONFIGURATION=true\
  -v $HOME/testslskd:/app -v $HOME/testslskd/Music:/music -v $HOME/testslskd/eBooks:/ebooks \
  -e "SLSKD_SHARED_DIR=/music;/ebooks" \
  --name slskd \
  slskd/slskd:latest
```

and the following `slskd.yml` config file:
```yml
debug: true
remote_configuration: true
instance_name: default
flags:
  no_logo: false
  no_start: false
  no_connect: false
  no_share_scan: false
  force_share_scan: false
  no_version_check: false
  log_sql: false
  experimental: false
  volatile: false
relay:
  enabled: false
  mode: debug # controller (default), agent, or debug (for local development)
  # controller config is required when running in 'agent' mode
  # this specifies the relay controller that will be controlling this agent
  controller:
    address: https://some.site.com:5000
    ignore_certificate_errors: false
    api_key: <a 16-255 character string corresponding to one of the controller's 'readwrite' or 'administrator' API keys>
    secret: <a 16-255 character shared secret matching the controller's config for this agent>
    downloads: false
  # agent config is optional when running in 'controller' mode
  # this specifies all of the agents capable of connecting
  agents:
    my_agent:
      secret: <a 16-255 character string unique to this agent>
      cidr: 0.0.0.0/0,::/0
directories:
  incomplete: ~
  downloads: ~
shares:
  directories:
    - ~
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
  cache:
    storage_mode: memory
    workers: 16
rooms:
  - ~
global:
  upload:
    slots: 20
    speed_limit: 1000
  download:
    slots: 500
    speed_limit: 1000
groups:
  default:
    upload:
      priority: 500
      strategy: roundrobin
      slots: 10
  leechers:
    thresholds:
      files: 1
      directories: 1
    upload:
      priority: 999
      strategy: roundrobin
      slots: 1
      speed_limit: 100
  # blacklisted:
    # members:
      # - <username to blacklist>
  user_defined:
    my_buddies:
      upload:
        priority: 250
        queue_strategy: firstinfirstout
        slots: 10
      members:
        - alice
        - bob
filters:
  search:
    request:
      - ^.{1,2}$
web:
  port: 5000
  https:
    disabled: false
    port: 5001
    force: false
    certificate:
      pfx: ~
      password: ~
  url_base: /
  content_path: wwwroot
  logging: false
  authentication:
    disabled: false
    username: slskd
    password: slskd
    jwt:
      key: ~
      ttl: 604800000
    api_keys:
      my_api_key:
        key: <some example string between 16 and 255 characters>
        role: readonly # readonly, readwrite, administrator
        cidr: 0.0.0.0/0,::/0
logger:
  loki: ~
metrics:
  enabled: false
  url: /metrics
  authentication:
    disabled: false
    username: slskd
    password: slskd
feature:
  swagger: true
soulseek:
  username: thisisatestuser
  password: password
  description: |
    A slskd user. https://github.com/slskd/slskd
  listen_port: 50000
  diagnostic_level: Info
  distributed_network:
    disabled: false
    disable_children: false
    child_limit: 25
    logging: false
  connection:
    timeout:
      connect: 10000
      inactivity: 15000
    buffer:
      read: 16384
      write: 16384
      transfer: 262144
      write_queue: 250
    proxy:
      enabled: false
      address: ~
      port: ~
      username: ~
      password: ~
integration:
  ftp:
    enabled: false
    address: ~
    port: ~
    username: ~
    password: ~
    remote_path: /
    encryption_mode: auto
    ignore_certificate_errors: false
    overwrite_existing: true
    connection_timeout: 5000
    retry_attempts: 3
  pushbullet:
    enabled: false
    access_token: ~
    notification_prefix: "From slskd:"
    notify_on_private_message: true
    notify_on_room_mention: true
    retry_attempts: 3
    cooldown_time: 900000
```

I don't see anything going very wrong in the container's log i.e.
```
...
[slskd.Shares.ShareService] [20:03:04 DBG] Recomputing share statistics...
[slskd.Shares.ShareService] [20:03:04 DBG] Share statistics updated
[slskd.Application] [20:03:04 INF] Share cache loaded from disk successfully. Sharing 0 directories and 0 files
[slskd.Application] [20:03:04 INF] Warming browse response cache...
[slskd.Application] [20:03:04 DBG] Saved cache to temp file /tmp/rb4ztogo.h5q
[slskd.Application] [20:03:04 INF] Browse response cached successfully in 14ms
[slskd.Application] [20:03:04 INF] Connected to the Soulseek server
[slskd.Application] [20:03:04 INF] Logged in to the Soulseek server as thisisatestuser
[slskd.Application] [20:03:04 WRN] Failed to check version: The input string '0-e4cd65ba' was not in a correct format.
[slskd.Users.UserService] [20:03:04 INF] Added user alice to watch list
[slskd.Users.UserService] [20:03:04 INF] Added user bob to watch list
```

so I'm wondering if I'm missing something in the config or somewhere else. Thanks 🙏
