### DISCUSSION TITLE
Having trouble with network shares - first time docker user

### DISCUSSION THREAD

**Discussion by funderarock** [slskd/slskd#938] [Q&A]
I am running docker on a windows 11 machine and trying to have it see folders on synology SMB volume and having quite a bit of trouble with it.  

This is my compose
```
version: '3.9'
services: 
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    ports:
      - 5222:5030
      - 5223:5031
      - 52222:50300
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_USERNAME=###
      - SLSKD_PASSWORD=###
      - SLSKD_SLSK_USERNAME=####
      - SLSKD_SLSK_PASSWORD=####
    volumes:
      - type: volume
        source: slsk
        target: /app
      - type: volume
        source: pmusic
        target: /music

volumes:
  slsk:
    driver_opts:
      type: cifs
      o: "username=###,password=`###`,vers=3.0"
      device: "//192.168.##.##/SLSK"
  pmusic:
    driver_opts:
      type: cifs
      o: "username=###,password=`###`,vers=3.0"
      device: "//192.168.##.##/Music" 
```

and this is the error I get back 
```
DriveLetter:\SLSK>docker-compose up -d
[+] Running 7/7
 ✔ slskd 6 layers [⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                                                                                     4.8s
   ✔ 9e3ea8720c6d Pull complete                                                                                                                                                                                                                       2.4s
   ✔ 2436f232d040 Pull complete                                                                                                                                                                                                                       2.6s
   ✔ 84e67bd42ad8 Pull complete                                                                                                                                                                                                                       2.6s
   ✔ 58be5e479a36 Pull complete                                                                                                                                                                                                                       2.6s
   ✔ 0b6931bf9d1d Pull complete                                                                                                                                                                                                                       2.6s
   ✔ bbd54a4a0174 Pull complete                                                                                                                                                                                                                       3.2s
[+] Running 3/1
 ✔ Network temp_slsk_default  Created                                                                                                                                                                                                                 0.6s
 ✔ Volume "temp_slsk_slsk"    Created                                                                                                                                                                                                                 0.0s
 ✔ Volume "temp_slsk_pmusic"  Created                                                                                                                                                                                                                 0.0s
 - Container slskd            Starting                                                                                                                                                                                                                0.1s
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:52222 -> 0.0.0.0:0: listen tcp 0.0.0.0:52222: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
```

I have run this without the shares as a simple "docker run" command and i got it to load just fine, connect to the network, search and download - though i have no idea where those downloads went and that got me started down the NAS share route.  I need to send files to the NAS as its where I will use the files in other ways.  Otherwise I looked into a complex chain of downloading locally,  moving files from a watched folder into the NAS with something already and opted for the cifs mounts as it seemed easier at the time.

If anyone can help a noob out and point out what I am doing wrong I would be textually appreciative.
