### ISSUE TITLE
Add the ability to restrict file extensions for groups

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#1033]
Although Soulseek is primarily about audio files, it is becoming increasingly common for users to share other, much larger, files like videos, ISOs, etc.

While working on #388 it occurred to me that in addition to controls over how much users can download and how often, some users may want to control what those users are able to download.  I'm still committed to building in features that negate the need for locked files!

Users should have the ability to opt user groups into or out of types of files by file extension, for example:

```yaml
groups:
  default:
    upload:
      priority: 500
      strategy: roundrobin
      slots: 10
    filetypes:
      include:
        - mp3
        - flac
      exclude:
        - mkv
        - mp4
  user_defined:
    my_buddies:
      upload:
        priority: 250
        strategy: firstinfirstout
        slots: 10
      filetypes: ~ # no restriction
      members:
        - alice
        - bob
```

Users should be able to define a list of 'included' filetypes, and any extension not on that list would be _excluded_.  Conversely users should be able to specify a list of 'excluded' filetypes and any extension not on that list would be _included_.  The example above should be valid, but is functionally redundant.

Filtering will need to be implemented when sending lists of files to other users:

* Search results
* Browse results
* Folder contents requests

Filters will also need to be applied when users attempt to download files.

Note that this filtering could be substituted for locked files, and that's not something I want to pursue at this time.
