### ISSUE TITLE
Change slskd user process under docker

### ISSUE THREAD

**Issue by toketin** [slskd/slskd#1043]
Hi, I've added on my compose both the version with `PUID=1000` and `PGID=100`, then the one with `user: "1000:100"`, but my app directory has still been created with root:root ownership. Even deleting itself and restarting again the container it doesn't work.

This leads to the error: `Directory /app is not writeable`.

This is my compose:

```
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    user: "1000:100" # PUID:PGID
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SLSK_USERNAME
      - SLSKD_SLSK_PASSWORD
    volumes:
      - /path/to/app/data:/app
      - /path/to/downloads:/app/downloads
    restart: unless-stopped
```
