### ISSUE TITLE
Excessive inotify watch usage/leak

### ISSUE THREAD

**Issue by melvyn2** [slskd/slskd#1050]
On both 0.18.2 and 0.19.5, slskd is hitting the inotify user watch limit on my system:
```
INotify Limits:
  max_queued_events    16,384
  max_user_instances   128
  max_user_watches     1,048,576
------------------------------------------------------------------------------
       Pid Uid        App                       Watches  Instances
    541393 992        slskd                    1,046,888          6
...
```
I'm sharing less than 15k files, so even with one watch per file and directory this should not be a problem. This causes problems around the rest of the OS which relies on inotify, like systemctl commands.

**Comment by melvyn2** [comment]
After launch, the watch count sometimes seems to stabilize if it doesn't reach the limit, but still remains very high. Right now I'm looking at 639,179 watches used, which is more than half of the limit.

**Comment by jpdillingham** [comment]
This will be rooted in the dotnet `FileSystemWatcher` that's used under the hood to react to configuration changes; nothing else in the application watches any files.  I can add a setting to disable automatic config reload on change, but with this enabled any config change will require a restart.

Can you share more about how you're running slskd? Every instance has this turned on and if this were a widespread issue I'd expect reports of crashing, so I'm thinking you may have a unique setup.

**Comment by melvyn2** [comment]
I'm running slskd through the nixos module, which results in the following systemd config:
```ini
# /etc/systemd/system/slskd.service
[Unit]
After=network.target
Description=A modern client-server application for the Soulseek file sharing network

[Service]
Environment=<nixos stuff>
EnvironmentFile=/srv/auth/slsk.env
ExecStart=/nix/store/300mj7mnyjk6z3f3h3kxhknp0nqgphxh-slskd-0.19.5/bin/slskd --app-dir /var/lib/slskd --config /nix/store/m8iwprrxqp03m4kw1rzccixszryagaay-slskd.yml
LockPersonality=true
NoNewPrivileges=true
PrivateDevices=true
PrivateMounts=true
PrivateTmp=true
PrivateUsers=true
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectProc=invisible
ProtectSystem=strict
ReadOnlyPaths=<path to share 1>
ReadOnlyPaths=<path to share 2>
ReadOnlyPaths=<path to share 3>
ReadOnlyPaths=<path to share 4>
ReadWritePaths=<path to downloads>
RemoveIPC=true
Restart=on-failure
RestrictNamespaces=true
RestrictSUIDSGID=true
StateDirectory=slskd
Type=simple
UMask=002
User=slskd
```

and the following config file:
```yaml
directories:
  downloads: <path to downloads>
filters:
  search: {}
flags:
  no_version_check: true
global:
  download: {}
  upload: {}
logger:
  disk: false
remote_configuration: false
remote_file_management: false
retention:
  files: {}
  transfers:
    download: {}
    upload:
      cancelled: 10
      errored: 60
      succeeded: 1440
shares:
  directories:
  - '[share1]<path to share 1>/'
  - '[share2]<path to share 2>'
  - '[share3]<path to share 3>'
  - '[share4]<path to share 4>'
soulseek:
  description: <user description>
  listen_port: 60277
web:
  port: 5030
  url_base: /
```
