### ISSUE TITLE
Problems starting slskd using docker-compose

### ISSUE THREAD

**Issue by nicholas-robertson** [slskd/slskd#110]
Launching slskd using `docker-compose up` and receiving the following error:

```
Attaching to soulseek
soulseek            | Failure processing application bundle.
soulseek            | Failed to determine location for extracting embedded files.
soulseek            | DOTNET_BUNDLE_EXTRACT_BASE_DIR is not set, and a read-write cache directory couldn't be created.
```

The compose file is as follows:
```
version: '3.3'
services:
    slsk-web-example:
        user: "1004:1004"
        ports:
            - '5000:5000'
            - '5001:5001'
        networks: 
            - web
        volumes:
            - '/home/main/downloads:/var/slskd/download'
            - '/home/main/music:/var/slskd/shared'
        environment:
            - SLSKD_SLSK_USERNAME=#######
            - SLSKD_SLSK_PASSWORD==#######
        container_name: soulseek
        restart: unless-stopped
        image: 'slskd/slskd:latest'
networks:
    web:
        external: true
```

Any help would be appreciated.

**Comment by jpdillingham** [comment]
Thanks for reporting this, I was able to reproduce it on my end.  It seems to only be an issue with docker-compose, as I can run the same exact image directly.  I'll have to investigate.

**Comment by jpdillingham** [comment]
The quick fix is to add the following environment variable:

```
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/var/tmp/.net
```

Info here: https://github.com/dotnet/runtime/issues/53346

I suspect that this is a problem with docker-compose and not docker because of the context in which the container is run.  I'll keep reading and figure out a permanent fix, which may end up being to set this envar directly in the Dockerfile.

**Comment by nicholas-robertson** [comment]
Adding the environment variable you found yields a different error:

```
Filesystem exception: Directory /var/slskd is not writeable: Access to the path '/var/slskd/628eed0a-844e-41f8-a605-4cc08f7553b7' is denied.
```

**Comment by jpdillingham** [comment]
You'll want to add a volume for `/var/slskd`.  With the addition of persisted data (via sqlite files) the container now expects an "app" directory for persistence.  Here's the current setup from the Dockerfile:

```
ENV SLSKD_APP_DIR=/var/slskd
ENV SLSKD_INCOMPLETE_DIR=/var/slskd/incomplete
ENV SLSKD_DOWNLOADS_DIR=/var/slskd/downloads
ENV SLSKD_SHARED_DIR=/var/slskd/shared
```

Unfortunately I don't have enough experience running containers as a specific user to say what the right thing to do is long term, but I'll do some more reading.

**Comment by jpdillingham** [comment]
To add more info here; the problem is that the .NET runtime tries to extract bundled files to the current user's home directory, but when specifying a user for the container this way, there is no such directory.  Thumbing through issues in the dotnet/runtime repo, it looks like this was done due to security concerns; users might be able to mess around with binaries owned by apps of other users.  This change is new for dotnet 5.

If I do nothing, this will remain a problem for anyone wanting to run as a user other than root, and they'll need to specify this environment variable.  If I bake this environment variable into the dockerfile, it creates the risk the runtime team was afraid of.

Given those two options I'm siding with baking it into the dockerfile, and will pin the directory to `/var/tmp/.net`, as it was for .NET Core 3 and below.  My rationale is that multi-user conflicts aren't really a concern inside of a container, but I'd be glad to hear dissenting opinions if anyone feels differently.

The next problem is that the built-in directories described above aren't writeable by users other than root, and users are forced to bind volumes with the correct permissions to get the app to run.  To resolve this, I'm going to change permissions for these directories to 777 after they are created.  Again, I'd be glad to hear any reasons why this shouldn't be done.

**Comment by jpdillingham** [comment]
This should be working with `slskd/slskd:canary` once it pushes (about 20 minutes from now) without the extra environment variable and volume.  Please have a look and reopen this issue if it still gives you problems.

**Comment by nicholas-robertson** [comment]
With the following docker-compose.yaml: 
```
version: '3.3'
services:
    slskd:
        user: "1004:1004"
        ports:
            - '5000:5000'
            - '5001:5001'
        networks:
            - web
        volumes:
            - '/opt/slsk/slskd/data:/var/slskd'
            - '/home/main/downloads:/var/slskd/downloads'
            - '/home/main/music:/var/slskd/shared'
        environment:
            - SLSKD_SLSK_USERNAME=######
            - SLSKD_SLSK_PASSWORD==######
        container_name: slskd
        restart: unless-stopped
        image: 'slskd/slskd:canary'
networks:
    web:
        external: true
```
Leads to to the following error: 
```
slskd    | Invalid configuration:
slskd    |   Directories:
slskd    |     The Incomplete field specifies a non-existent directory '/var/slskd/incomplete'.
```
Despite the directory `/opt/slsk/slskd/data` containing the following folders (created by the container):
```
drwxr-xr-x 2 root root 4.0K Jul  7 15:22 downloads
drwxr-xr-x 2 root root 4.0K Jul  7 15:26 incomplete
drwxr-xr-x 2 root root 4.0K Jul  7 15:22 shared
```

Adding `'/opt/slsk/slskd/incomplete:/var/slskd/incomplete'` to the volumes leads to this error:
```
slskd    | Filesystem exception: Directory /var/slskd is not writeable: Access to the path '/var/slskd/b298851a-98a6-467d-be9d-1e5c33b41f4f' is denied.
slskd    | Filesystem exception: Directory /var/slskd is not writeable: Access to the path '/var/slskd/88b16877-7569-4f15-98e3-1a40f9bba27e' is denied.
slskd exited with code 0
slskd    | Filesystem exception: Directory /var/slskd is not writeable: Access to the path '/var/slskd/1c781415-61ad-4554-86b1-adae6a6f92a2' is denied.
slskd exited with code 0
```

**Comment by jpdillingham** [comment]
With this `docker-compose.yml`:

```yml
version: '3.3'
services:
    slskd:
        user: "1004:1004"
        ports:
            - '5000:5000'
            - '5001:5001'
        volumes:
            - '/opt/slsk/slskd/data:/var/slskd'
        environment:
            - SLSKD_SLSK_USERNAME=######
            - SLSKD_SLSK_PASSWORD==######
        container_name: slskd
        restart: unless-stopped
        image: 'slskd/slskd:canary'
```

And this filesystem:

```
ls -la /opt/slsk/slskd/data
drwxr-xr-x 5 root root 4096 Jul  8 08:32 .
drwxr-xr-x 3 root root 4096 Jul  8 08:31 ..
drwxr-xr-x 2 root root 4096 Jul  8 08:32 downloads
drwxr-xr-x 2 root root 4096 Jul  8 08:32 incomplete
drwxr-xr-x 2 root root 4096 Jul  8 08:32 shared
```

I get:

```
Filesystem exception: Directory /var/slskd is not writeable: Access to the path '/var/slskd/22bf1a6f-e298-46ef-bb82-4b98e01b6efb' is denied.
```

I ran `sudo chmod -R 777 /opt/slsk/slskd/data` and `docker-compose up` works as expected.

For context, `22bf1a6f-e298-46ef-bb82-4b98e01b6efb` is a random file that the code tries to write on startup to confirm that it has write access to the directory.

Let me know if that helps!

**Comment by nicholas-robertson** [comment]
With the following step I got it to work. 

1. Manually creating the following the following directory structure. I specified the name of the `data` directory in `docker-compose.yaml` but the rest must stay the same. 
```
$ tree /opt/slskd

├── data
│   ├── downloads
│   ├── incomplete
│   └── shared
└──  docker-compose.yaml
```
2. Run  `sudo chmod -R 777 data` 
3. Run `docker-compose up -d`
4. Check `docker logs` in order to verify the start-up went smoothly.


My docker-compose is as follows:
```
version: '3.3'
services:
    slskd:
        user: "1004:1004"
        ports:
            - '5000:5000'
            - '5001:5001'
        volumes:
            # download dir
            - '/home/main/downloads:/var/slskd/downloads'
            # slskd data dir
            - '/opt/slskd/data:/var/slskd'
        environment:
            - SLSKD_SLSK_USERNAME=####
            - SLSKD_SLSK_PASSWORD=####
        container_name: slskd
        restart: unless-stopped
        image: 'slskd/slskd:canary'
```
