### ISSUE TITLE
Unexpected behaviour from leechers thresholds

### ISSUE THREAD

**Issue by TH0MVS** [slskd/slskd#1105]
Hello,

People who share at least 2 files or 2 directories are still able to download. I expect leechers to download only 1 file per week if they share less than 2000 files or 100 directories. Here is my configuration.

Thanks for your help, keep up the great work !

```
global:
  upload:
    slots: 10
    speedLimit: 2147483647
  limits:
    queued:
      files: null
      megabytes: null
      failures: null
    daily:
      files: null
      megabytes: null
      failures: null
    weekly:
      files: null
      megabytes: null
      failures: null
  download:
    slots: 2147483647
    speedLimit: 2147483647
groups:
  default:
    upload:
      priority: 1
      strategy: roundrobin
      slots: 2147483647
      speedLimit: 2147483647
    limits:
      queued:
        files: null
        megabytes: null
        failures: null
      daily:
        files: null
        megabytes: null
        failures: null
      weekly:
        files: 1000
        megabytes: null
        failures: 250
  leechers:
    thresholds:
      files: 2000
      directories: 100
    upload:
      priority: 999
      strategy: roundrobin
      slots: 2147483647
      speedLimit: 2147483647
    limits:
      queued:
        files: null
        megabytes: null
        failures: null
      daily:
        files: null
        megabytes: null
        failures: null
      weekly:
        files: 1
        megabytes: null
        failures: 1
```
