### ISSUE TITLE
Trying to add username/pw into options.

### ISSUE THREAD

**Issue by techdixie** [slskd/slskd#1166]
Hey. I'm pretty new to self hosting so excuse me if this is rather simple. I go into the settings/options, click edit, scroll down to

soulseek:
  address: vps.slsknet.org
  port: 2271
  username: null
  password: null

and enter my username and password. When I try to hit save I get "Value cannot be null. (Parameter 'instance')".

What am I doing wrong?!  Thank you for your time.

**Comment by jpdillingham** [comment]
That's a pretty non-specific error, but I'd guess it just means that your YAML syntax is off.  Make sure you're retaining indentation, like this:

```yaml
soulseek:
  address: vps.slsknet.org
  port: 2271
  username: <your name>
  password: <your password>
```
