### ISSUE TITLE
The removed records have never been deleted from the Transfers table

### ISSUE THREAD

**Issue by vitoyucepi** [slskd/slskd#1192]
## Summary

I've investigated why some transfers fail with errors and there are timeouts in logs and found out that the size of the `transfers.db` grew to 200MB in the last 6 months.

## Details

I've made the following changes to reduce the size of the table:
1. Connect to the database using `sqlite3 transfers.db`.
1. List tables in the database using `.tables`.
1. Inspect the `Transfers` table schema using `.schema Transfers`.
1. Retrieve the first 10 records from the table using `select * from Transfers limit 10;`. These records were all from the time when the database was created and had the flag `Removed=1`.
1. Use the query `select count(*) from Transfers;` to determine the number of rows in the table.
   After a week, there were 6000 rows.
1. Get the count of Removed records by using `select count(*) from Transfers where Removed=1;`.
   5000 records were marked as removed in a week.
1. Remove the records marked as removed manually using `delete from Transfers where Removed=1;`.
1. Use `VACUUM;` to reduce the database size to a minimum.

![Prometheus graphs with the CPU consumption before and after manual cleanup](https://github.com/user-attachments/assets/c4d6ca37-67cf-45a4-846b-6482af4b709f)

I use the following settings
```env
SLSKD_SHARED_DIR="/app/shared"
SLSKD_SHARE_CACHE_STORAGE_MODE="disk"
SLSKD_SHARE_CACHE_WORKERS=1
SLSKD_DISK_LOGGER=false
SLSKD_REMOTE_CONFIGURATION=false
SLSKD_REMOTE_FILE_MANAGEMENT=false
SLSKD_NO_VERSION_CHECK=true
SLSKD_NO_LOGO=true
SLSKD_NO_HTTPS=true
SLSKD_METRICS=true
SLSKD_UPLOAD_SPEED_LIMIT=4000
```
```yaml
---
groups:
  default:
    upload:
      priority: 500
      strategy: firstinfirstout
      slots: 10
  leechers:
    upload:
      priority: 999
      strategy: firstinfirstout
      slots: 2
      speed_limit: 1000

retention:
  transfers:
    upload:
      succeeded: 2880 # 2 days
      errored: 720 # 12 hours
      cancelled: 720 # 12 hours
    download:
      succeeded: 10080 # 1 week
      errored: 20160 # 2 weeks
      cancelled: 1440 # 1 day
```

## Actual behavior

It seems the Uploads/Downloads log has never been removed when the retention is active.

## Expected behavior

The records that have been removed should be cleaned up from the `Transfers` table.

## Versions

- slskd: 0.21.3
