### ISSUE TITLE
[BUG] Permission issues with files created by slskd (docker)

### ISSUE THREAD

**Issue by deafmute1** [slskd/slskd#1223]
When using the docker container, I have multiple severe issues with permissions and umask settings.

1. The guide says the container supports using `user: uid:gid` in compose. It seems to work, and files and folders are created using this user. However, for some reason when moving from incomplete to download folder, there is an error like: ` Access to the path /app/incomplete/AlbumName is denied`. This is despite slskd managing to create the files successfully with the correct umask and ownership - i.e. it is not an error with the parent folders permissions, but with slskd writing a file to disk it lacks the perms to read/move???

4. If I remove the `user` option, slskd manages to move complete files. However, the files appear to be created with umask `000` e.g. with no perms at all, even for the owner (which is now `root`)! The folder is created with expected perms for a 022 umask (755), but not the files.

**Comment by jpdillingham** [comment]
Can you share your compose configuration and any environment variables or other configuration changes you've made? (other than username and password of course)

**Comment by deafmute1** [comment]
docker compose: 
```  
slskd:
    image: slskd/slskd
    #user: "1001:1001"
    ports:
      - 50300:50300/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.slskd.entrypoints=websecure
      - traefik.http.routers.slskd.rule=Host(`slsk.l.def.au`)
      - traefik.http.routers.slskd.middlewares=private-ip-only@file
      - traefik.http.services.slskd.loadbalancer.server.port=5030
      - traefik.http.routers.slskd.tls=true
      - traefik.http.routers.slskd.tls.certresolver=acme-dns-cf
    networks:
      - default
      - proxy
    volumes:
      - /var/ddata/autoget/slskd:/app
      - /srv/mergerfs/mergerfs/media/music:/media/music
    restart: unless-stopped
```
[slskd.yaml.txt](https://github.com/user-attachments/files/17320708/slskd.yaml.txt)
