### ISSUE TITLE
SLL and certificate error

### ISSUE THREAD

**Issue by FaGuoMa** [slskd/slskd#1267]
First of all, maintainers please accept all the love in the world!

**My issue**
I set up the "basic" 5031 for SSL
```
web:                                                                                                                                   
   port: 5030                                                                                                                           
   https:                                                                                                                               
     disabled: false                                                                                                                    
     port: 5031                                                                                                                         
     force: false                                                                                                                       
     certificate:                                                                                                                       
       pfx: /slskd/slskd.pfx                                                                                                            
       password: <some long password>
```
I used the slkd to force cert generation, and the config manager (UI) correctly finds the pfx (which I know since it won't accept incorrect path). Passwrd is the one auto-generated

I then try to access through 5031 and I just get "empty response" 

I use the latest docker image, which I run on my synology. Non SSL works like a charm, and I would rather not use nginx if I can avoid it since it's part of the base synology os distro. Besides, I have a good firewall management at the home network level (unifi)
