### ISSUE TITLE
slskd Fails to Substitute Environment Variables Despite Being Set in Docker

### ISSUE THREAD

**Issue by kmlbgn** [slskd/slskd#1273]
The environment variables set in `~/.bashrc` on a VPS and passed correctly into the Docker container running slskd are note being picked up. As a result, slskd uses the config file instead and the logs from slskd show the placeholder `${SLSKD_SLSK_USERNAME}` instead of the actual username.

# My current config

## docker-compose.yml
```
version: "3.8"
services:
  slskd:
    image: slskd/slskd:latest
    container_name: slskd
    environment:
      - SLSKD_SLSK_USERNAME=${SLSKD_SLSK_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
      - SLSKD_USERNAME=${SLSKD_USERNAME}
      - SLSKD_PASSWORD=${SLSKD_PASSWORD}
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    volumes:
      - /home/slskd:/app:rw
      - /home/music:/music:rw
    user: 1000:1000
    restart: always
```

## vps ~/.bashrc:

```
export SLSKD_SLSK_USERNAME="user"
export SLSKD_SLSK_PASSWORD="password"
export SLSKD_USERNAME="ui_username"
export SLSKD_PASSWORD="ui_password"
```

## slskd.yml (relevant portion):
```
web:
  authentication:
    disabled: false
    username: ${SLSKD_USERNAME}
    password: ${SLSKD_PASSWORD}
soulseek:
  address: vps.slsknet.org
  port: 2271
  username: ${SLSKD_SLSK_USERNAME}
  password: ${SLSKD_SLSK_PASSWORD}
  ```
  
# Problem & logs verification

When running `docker exec -it slskd printenv` on vps terminal, the environment variables are confirmed to be correctly set inside the container:

```
...
SLSKD_SLSK_USERNAME=user
SLSKD_SLSK_PASSWORD=password
SLSKD_USERNAME=ui_username
SLSKD_PASSWORD=ui_password
...
```

However, the slskd logs still show the placeholder `${SLSKD_SLSK_USERNAME}` instead of the actual username:

```
[09:34:52 INF] Logged in to the Soulseek server as ${SLSKD_SLSK_USERNAME}
 ```
 
<img width="372" alt="image" src="https://github.com/user-attachments/assets/38e95596-c693-442d-8247-eec3bb852e3d" />

 
 also slskd UI login do not work but work using the respective placehodlers `${SLSKD_USERNAME}` as is
