### ISSUE TITLE
[Feature Request] Add retention setting for Events and Transfers

### ISSUE THREAD

**Issue by TH0MVS** [slskd/slskd#1305]
It would be nice to have some more retention settings, for the following files : events.db-wal, transfers.db-wal, transfers.db, events.db.

I dont use logs and correct me if I'm wrong, but THEY are logs. These files tend to be bigger and bigger on my setup and the only workaround I find is to delete and redeploy my docker stack.

Something like :
```
retention:
  search: 1440
  transfers:
    upload:
      succeeded: 5
      errored: 5
      cancelled: 5
    download:
      succeeded: null
      errored: null
      cancelled: null
  files:
    complete: null
    incomplete: null
  logs: 1
  **events : 1 (day)**
  **transfers : 7 (days)**
```
