### ISSUE TITLE
UI Password Change

### ISSUE THREAD

**Issue by congresstart** [slskd/slskd#1316]
Hey all,

Sorry to ask but I'm struggling to change the default password using Windows.

I've attempted with the two yaml types below but the [UI only sees the default password. 
](https://imgur.com/lTC7Lzu)

This is the right YAML I'm editing as other changes have been made such as shares. 

```
   web:
     port: 5030
#     https:
#      disabled: false
#      port: 5031
#      force: false
#      certificate:
#        pfx: ~
#        password:
#   url_base: /
#   content_path: wwwroot
   logging: true
   authentication:
     disabled: false
     username: user1
     password: changeme
```

  ```
 web:
     port: 5030
     https:
      disabled: false
      port: 5031
      force: false
      certificate:
        pfx: ~
        password:
   url_base: /
   content_path: wwwroot
   logging: true
   authentication:
     disabled: false
     username: user1
     password: changeme
```

**Comment by jpdillingham** [comment]
YAML is particular about formatting, and it looks like you've got a mix of 1/3 spaces when there should be precisely 2 spaces per level of indent.  Try this:

```yaml
web:
  authentication:
    disabled: false
    username: change
    password: me
```
