### ISSUE TITLE
API Key Configuration Potential Docker issue

### ISSUE THREAD

**Issue by bastienboutonnet** [slskd/slskd#1318]
I was about to configure an API key for slskd and added the following to the system config (as shown in the [docs](https://github.com/slskd/slskd/blob/master/docs/config.md#authentication)
```yaml
web:
  authentication:
    disabled: false
    username: slskd
    password: slskd
    api_keys:
      my_api_key:
        key: "my_key"
        cidr: "0.0.0.0/0,::/0"
```

However I get a parsing error `While parsing a block mapping, did not find expected key.`

I checked indentations and so on but all seems good. Tried with and without quotes. My feeling is that maybe this is to do with the fact that i haven't used `--generate-api-key` on application startup. The issue is that because I'm deploying via docker I can't quite do that I'm afraid.

Any tips?
