### ISSUE TITLE
[Feature Request] Easier way to see and browse the files of those downloading from you

### ISSUE THREAD

**Issue by ItsNoted** [slskd/slskd#1319]
Sometimes I get users who download a lot of files. I like to see how much they are sharing sometimes to see if they are being just as generous or only sharing a few files to get what they want. Also an easy way to ban them from the download page. I'm trying to transfer from using Nicotine+ to slskd.

**Comment by jpdillingham** [comment]
The built-in 'leechers' [user group](https://github.com/slskd/slskd/blob/master/docs/config.md#built-in-groups) is designed to handle this concern.  From slskd.example.yml:

```yaml
  leechers:
    thresholds:
      files: 1
      directories: 1
    upload:
      priority: 999
      strategy: roundrobin
      slots: 1
      speed_limit: 100
    limits:
      queued:
        files: 15
        megabytes: 150
      daily:
        files: 30
        megabytes: 300
        failures: 10
      weekly:
        files: 150
        megabytes: 1500
        failures: 30
```

This configuration will limit any user that's sharing less than 1 file in 1 directory to downloading 1 file at a time at 100kb/s, and further limits the number of files they can enqueue at any time or download in a given day or week.

This is designed to encourage people to share while also allowing them to get the files they want without imposing much of a load.

If you want to go further and ban users, you'll have to do it through edits to the YAML file either in the UI or on disk; programmatic edits aren't supported at the moment.
