### ISSUE TITLE
[32 bit OS on ARM64 hardware] System.Runtime.InteropServices.COMException from armv7 Docker image

### ISSUE THREAD

**Issue by bboggess** [slskd/slskd#1339]
I am attempting to run slskd in a Docker container on my Raspberry Pi. However, slskd is crashing on startup almost immediately every time I launch the container. I have a few other unrelated containers running on the same device without issue. I don't run into this issue when directly running the slskd binary and not going through a container.

Here is the output, showing the exception info:

```
slskd-1  |
slskd-1  |
slskd-1  |                     ▄▄▄▄     ▄▄▄▄     ▄▄▄▄
slskd-1  |               ▄▄▄▄▄▄█  █▄▄▄▄▄█  █▄▄▄▄▄█  █
slskd-1  |               █__ --█  █__ --█    ◄█  -  █
slskd-1  |               █▄▄▄▄▄█▄▄█▄▄▄▄▄█▄▄█▄▄█▄▄▄▄▄█
slskd-1  | ╒════════════════════════════════════════════════════════╕
slskd-1  | │           GNU AFFERO GENERAL PUBLIC LICENSE            │
slskd-1  | │                   https://slskd.org                    │
slskd-1  | │                                                        │
slskd-1  | │              0.22.2.0 (0.22.2.0+a2e1e65b)              │
slskd-1  | └────────────────────────────────────────────────────────┘
slskd-1  | Unhandled exception. System.Runtime.InteropServices.COMException (0x8007054F): An internal error occurred.
slskd-1  |  (0x8007054F)
slskd-1  |    at System.Threading.WaitHandle.WaitOneCore(IntPtr waitHandle, Int32 millisecondsTimeout)
slskd-1  |    at System.Threading.WaitHandle.WaitOneNoCheck(Int32 millisecondsTimeout)
slskd-1  |    at System.Threading.TimerQueue.TimerThread()
slskd-1  |    at System.Threading.Thread.StartCallback()
slskd-1  | Fatal error. Internal CLR error. (0x80131506)
slskd-1  |    at System.Threading.WaitHandle.WaitOneCore(IntPtr, Int32)
slskd-1  |    at System.Threading.WaitHandle.WaitOneNoCheck(Int32)
slskd-1  |    at System.Threading.TimerQueue.TimerThread()
slskd-1  |    at System.Threading.Thread.StartCallback()
slskd-1  | Aborted
```

For context, here is my docker-compose file. I'm pretty much following the standard template from the documentation here.
```
services:
  slskd:
    image: slskd/slskd:0.22.2
    restart: unless-stopped
    environment:
      - "SLSKD_SHARED_DIR=/music"
      - "SLSKD_SLSK_USERNAME=***"
      - "SLSKD_SLSK_PASSWORD=***"
      - "SLSKD_USERNAME=***"
      - "SLSKD_PASSWORD=***"
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    volumes:
      - "/var/slskd:/app:rw"
      - "/media/f86eae2b-509e-460e-86f7-4a04a4e66d9a/music:/music:ro"
    user: 1000:1000
```

I'm running volumio on the Pi, which I believe is just a fork of Raspbian. The output of `lscpu` is
```
Architecture:        armv7l
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           ARM
Model:               3
Model name:          Cortex-A72
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            270.00
Flags:               half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
```
