### ISSUE TITLE
Add retention settings for database records and pre-migration backups

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#1344]
Here are the retention settings at the time of writing:

```yaml
retention:
  search: 10080 # 7 days, in minutes
  transfers:
    upload:
      succeeded: 1440 # 1 day, in minutes
      errored: 30
      cancelled: 5
    download:
      succeeded: 1440 # 1 day, in minutes
      errored: 20160 # 2 weeks, in minutes
      cancelled: 5
  files:
    complete: 20160 # 2 weeks, in minutes
    incomplete: 43200 # 30 days, in minutes
  logs: 180 # days
```

The `transfers` retention settings dictate when records are removed from the UI, not the database; records are retained forever.  As the application ages, high-volume users will likely need a way to clean this data up to control database size.

Additionally, I'm working on a feature that adds database migrations, and prior to performing migrations database backups are taken.  These backups will double the size of database storage, and unless data was lost or mangled by a migration the backups are of little use and should be deleted.

Add a section to retention options, like:

```yaml
retention:
  database:
    transfers: <duration to retain individual records>
    ... other tables ...
    backups: <duration to keep pre-migration backups>
```

And of course, the logic that will actually do the cleanup will be needed as well.
