### ISSUE TITLE
How do I run the container read-only?

### ISSUE THREAD

**Issue by UtkarshVerma** [slskd/slskd#1348]
I like to run my containers read-only to follow security practices, and it makes backups deterministic too. Here is my docker compose file:

```yaml
include:
  - ../traefik/compose.yaml

services:
  slskd:
    container_name: slskd
    image: docker.io/slskd/slskd:latest

    user: $PUID:$PGID
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL

    networks:
      - traefik

    expose:
      - 5030

    environment:
      SLSKD_USERNAME: $SLSKD_USER
      SLSKD_PASSWORD: $SLSKD_PASSWORD
      SLSKD_SLSK_USERNAME: $SLSK_USERNAME
      SLSKD_SLSK_PASSWORD: $SLSK_PASSWORD
      SLSKD_REMOTE_CONFIGURATION: true
      SLSKD_SHARED_DIR: "/music;/books"

    labels:
      traefik.enable: true
      traefik.http.routers.slskd.rule: Host(`slskd.$DOMAIN`)
      traefik.http.routers.slskd.entrypoints: websecure
      traefik.http.routers.slskd.tls.certresolver: le

    tmpfs:
      - /.net/slskd:uid=$PUID,gid=$PGID

    volumes:
      - ./state:/app:rw
      - $DATA_DIR/media/music:/music:rw
      - $DATA_DIR/media/books:/books:rw

    restart: unless-stopped
```

However, when I run this, I get the error:

```
slskd  | Unhandled exception. System.TypeInitializationException: The type initializer for 'slskd.Program' threw an exception.
slskd  |  ---> System.IO.IOException: The system cannot open the device or file specified. : '42335EE2DA436D3907CE87E372511838B58E284E8225E9722251DCDC3BDB8FEA'
slskd  |    at System.Threading.Mutex.CreateMutexCore(Boolean initiallyOwned, String name, Boolean& createdNew)
slskd  |    at System.Threading.Mutex..ctor(Boolean initiallyOwned, String name)
slskd  |    at slskd.Program..cctor()
slskd  |    --- End of inner exception stack trace ---
slskd  |    at slskd.Program.Main(String[] args)
slskd  | Aborted (core dumped)
slskd exited with code 134
```

Any help would be highly appreciated.

**Comment by jpdillingham** [comment]
Have a look at #1004 and see if that solves the problem.  If so I'll figure out where that can be documented.

**Comment by UtkarshVerma** [comment]
Thanks for the quick response. I tried this now:

```yaml
include:
  - ../traefik/compose.yaml

services:
  slskd:
    container_name: slskd
    image: docker.io/slskd/slskd:latest

    user: $PUID:$PGID
    # TODO: Wait for https://github.com/slskd/slskd/issues/1348
    read_only: true
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL

    networks:
      - traefik

    expose:
      - 5030

    environment:
      DOTNET_BUNDLE_EXTRACT_BASE_DIR: /tmp/.net
      SLSKD_USERNAME: $SLSKD_USER
      SLSKD_PASSWORD: $SLSKD_PASSWORD
      SLSKD_SLSK_USERNAME: $SLSK_USERNAME
      SLSKD_SLSK_PASSWORD: $SLSK_PASSWORD
      SLSKD_REMOTE_CONFIGURATION: true
      SLSKD_SHARED_DIR: "/music;/books"

    labels:
      traefik.enable: true
      traefik.http.routers.slskd.rule: Host(`slskd.$DOMAIN`)
      traefik.http.routers.slskd.entrypoints: websecure
      traefik.http.routers.slskd.tls.certresolver: le

    tmpfs:
      - /tmp

    volumes:
      - ./state:/app:rw
      - $DATA_DIR/media/music:/music:rw
      - $DATA_DIR/media/books:/books:rw

    restart: unless-stopped

```

But this gives a new error:

```
slskd  |
slskd  |
slskd  |                     ▄▄▄▄     ▄▄▄▄     ▄▄▄▄
slskd  |               ▄▄▄▄▄▄█  █▄▄▄▄▄█  █▄▄▄▄▄█  █
slskd  |               █__ --█  █__ --█    ◄█  -  █
slskd  |               █▄▄▄▄▄█▄▄█▄▄▄▄▄█▄▄█▄▄█▄▄▄▄▄█
slskd  | ╒════════════════════════════════════════════════════════╕
slskd  | │           GNU AFFERO GENERAL PUBLIC LICENSE            │
slskd  | │                   https://slskd.org                    │
slskd  | │                                                        │
slskd  | │              0.22.5.0 (0.22.5.0+7b99d333)              │
slskd  | └────────────────────────────────────────────────────────┘
slskd  | [23:50:24 INF] Version: 0.22.5.0 (0.22.5.0+7b99d333)
slskd  | [23:50:24 INF] System: .NET 8.0.15, Unix 6.12.26.0, 64 bit, 4 processors
slskd  | [23:50:24 INF] Process ID: 8 (64 bit)
slskd  | [23:50:24 INF] Invocation ID: 650a52d8-6c04-4b04-a636-7c2b42eeb3f4
slskd  | [23:50:24 INF] Instance Name: default
slskd  | [23:50:24 INF] Configuring application...
slskd  | Unhandled exception. System.DllNotFoundException: Unable to load shared library 'e_sqlite3' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
slskd  | /tmp/.net/slskd/ZBEMVJyEzLk062a4kBTsmuedF7AX62U=/e_sqlite3.so: cannot open shared object file: No such file or directory
slskd  | /slskd/e_sqlite3.so: cannot open shared object file: No such file or directory
slskd  | /tmp/.net/slskd/ZBEMVJyEzLk062a4kBTsmuedF7AX62U=/libe_sqlite3.so: failed to map segment from shared object
slskd  | /slskd/libe_sqlite3.so: cannot open shared object file: No such file or directory
slskd  | /tmp/.net/slskd/ZBEMVJyEzLk062a4kBTsmuedF7AX62U=/e_sqlite3: cannot open shared object file: No such file or directory
slskd  | /slskd/e_sqlite3: cannot open shared object file: No such file or directory
slskd  | /tmp/.net/slskd/ZBEMVJyEzLk062a4kBTsmuedF7AX62U=/libe_sqlite3: cannot open shared object file: No such file or directory
slskd  | /slskd/libe_sqlite3: cannot open shared object file: No such file or directory
slskd  |
slskd  |    at SQLitePCL.SQLite3Provider_e_sqlite3.NativeMethods.sqlite3_libversion_number()
slskd  |    at SQLitePCL.SQLite3Provider_e_sqlite3.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
slskd  |    at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
slskd  |    at SQLitePCL.Batteries_V2.Init()
slskd  |    at SQLitePCL.Batteries.Init()
slskd  |    at slskd.Program.InitSQLiteOrFailFast()
slskd  |    at slskd.Program.Main(String[] args)
```
