### ISSUE TITLE
socks5 not displaying output when in use via config

### ISSUE THREAD

**Issue by radicalhashcan** [slskd/slskd#199]
Currently have the configuration of a socks 5 w/ auth however even with diagnostic level set to info (default i believe) there is unfortunately no output stating that a proxy is in fact being utilized below i have included an example of the current config setting incase i have missed anything.

   connection:
     timeout:
       connect: 10000
       inactivity: 15000
     buffer:
       read: 16384
       write: 16384
     proxy:
       address: 0.0.0.0 (example)
       port: 1080
       username: 123
       password: 123

**Comment by jpdillingham** [comment]
The default yaml file is missing an `enabled` property for the proxy, which is probably what is causing this.

With this config:

```yaml
soulseek:
  connection:
    proxy:
      enabled: true
      address: 192.168.1.1
      port: 80
      username: foo
      password: bar
```

You should see logs similar to the following on startup (the ordering changed recently, the 'Using Proxy` is what you're looking for):

```
[slskd.Application] [] [10:31:26 INF] Client configured
[slskd.Application] [] [10:31:26 INF] Listening on port 50025
[slskd.Application] [] [10:31:26 INF] Using Proxy 192.168.1.1:80
```
