### ISSUE TITLE
Add VPN to Docker container

### ISSUE THREAD

**Issue by screwfaze** [slskd/slskd#222]
I would like to request a feature to have this docker container running through a VPN connection like haugene/transmission-openvpn does.

Thanks

**Comment by GordonFreemanK** [comment]
I agree with @rakbladsvalsen, containers are supposed to be linked together, not have multiple applications running in a single one. You want to have one container per app so each app corresponds exactly to what you need. People who want to use slskd without VPN shouldn't have to have a VPN app loaded that they don't use, particularly an OpenVPN one. Use qdm12/gluetun, linuxserver/wireguard or any VPN that corresponds to your specific needs and connect it to the slskd container, literally the only thing you need to do that is `network_mode: service:vpn`.

**Comment by jpdillingham** [comment]
@rakbladsvalsen @GordonFreemanK thanks for your input!

I was hesitant to do this work because I wasn't sure what best practice was, and didn't really want to increase the size of the container image as I've done quite a bit of work to try and get it as small as possible.

Given the rationale in the discussion here, I'll close this as `wontfix`.

**Comment by iamwoz** [comment]
> IMO this shouldn't be up to slskd since you can already have this sort of container-through-VPN with images like gluetun, or openvpn client.
> 
> https://github.com/qdm12/gluetun
> 
> Gluetun works fairly well, supports tons of VPNs and is really small. I use it with slskd and well, "it just works".

I've tried setting this up and my uploads seem to work fine, but my downloads mostly fail with: Transfer aborted, the remote size of 0 does not match expected size

I've I retry my downloads enough they will eventually work - did you do anything special with your gluetun setup?

**Comment by FrenchGithubUser** [comment]
Gluetun works pretty well indeed. With qbittorrent, there is an extra container to update the forwarded port (as it may often change with some vpn providers). But what about slskd ? Is there a way to forward a non-static port with slskd running through gluetun ?

**Comment by GordonFreemanK** [comment]
> Gluetun works pretty well indeed. With qbittorrent, there is an extra container to update the forwarded port (as it may often change with some vpn providers). But what about slskd ? Is there a way to forward a non-static port with slskd running through gluetun ?

You don't need to have a dynamic port, you can choose whichever you want (possibly have to be over 16386?) in slskd.yaml
```
soulseek:
  username: xxx
  password: xxx
  listen_port: <port_here>
```

And you also don't need to use a different container to forward ports in the VPN, as long as your provider allows you setting up port forwarding you can use this environment variable in the gluetun container to allow ingress in the firewall that's integrated to that container: `FIREWALL_VPN_INPUT_PORTS=<port_here>,<other_port_here>,etc`

**Comment by FrenchGithubUser** [comment]
The thing is that the forwarded port changes very often (in the case of ProtonVPN for example), so changing it in the configuration file manually is not an option.

Or am I missing something ?

**Comment by GordonFreemanK** [comment]
No that makes sense.

**Comment by Fran314** [comment]
EDIT: This configuration doesn't actually work. The port results open and users seem to able to connect to it, but upon download the other user get a `Connection closed` error and I keep getting a `Connection reset by peer` error.

Sorry for commenting on an old issue, but I found a workaround to make gluetun+slskd work and I thought it might be useful to share.

Since gluetun's v3.40 (latest release at the time of writing) you can use gluetun's `VPN_PORT_FORWARDING_UP_COMMAND` option combined with the fact that slskd hot-reloads the configuration file to automatically update the forwarded port when it changes in gluetun.

My configuration looks something like this

```yaml
services:
  gluetun:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      VPN_SERVICE_PROVIDER: protonvpn
      OPENVPN_USER: ${OPENVPN_USER}+pmp
      OPENVPN_PASSWORD: ${OPENVPN_PASSWORD}
      SERVER_COUNTRIES: Switzerland
      SERVER_CITIES: Zurich
      VPN_PORT_FORWARDING: on
      VPN_PORT_FORWARDING_UP_COMMAND: >
        '/bin/sh -c "sed -i 's/listen_port:.*/listen_port\: {{PORTS}}/' /app/slskd.yml"'

    ports:
      - 5030:5030
      - 5031:5031
    volumes:
      - ./app:/app
    restart: unless-stopped
  slskd:
    image: slskd/slskd:0.23.1
    container_name: slskd
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ./app:/app
    network_mode: 'service:gluetun'
    restart: unless-stopped
```

Note-worthy details in the configuration:
- both slskd and gluetun have access to the volume `./app`. I'm not sure this is 100% conventional, but this allows the gluetun service to access (and write to) the configuration file for slskd, that is `/app/slskd.yaml` (which is the one overwritten in `VPN_PORT_FORWARDING_UP_COMMAND`)
- in `./app/slskd.yaml`, the lines needed to specify the `listen_port` must be uncommented, otherwise even when the value of the port gets overwritten, it will not be seen and will not get applied
- the port binding `5030:5030` and `5031:5031` are done on gluetun's side since slskd uses gluetun's network
- the `VPN_PORT_FORWARDING_UP_COMMAND` is written as a multiline string, which requires the environment variables to be specified with the mapping syntax instead of the list syntax. I have found no way around this
- in the given configuration, the values `OPENVPN_USER` and `OPENVPN_PASSWORD` are inside a `.env` file for privacy concerns

I have not stress-tested this but it seems to work fine

Shoutout to [this project](https://github.com/tieum/slskd-port-forward-gluetun-server) for the inspiration

**Comment by ovizii** [comment]
Sorry for resurrecting this old thread, but I couldn't find any better one using gluetun + slskd. 

gluetun is working perfectly fine for all other apps except slskd. I even tried using an IP isntaed of the server name to rule out DNS problems but slskd simply doesn't want to work through gluetun.

```
soulseek:
  address: 208.76.170.59 
  port: 2271 # 2242 either port should work
```

Any ideas if there is something special needed to get slskd working through gluetun?

**Comment by gwarf** [comment]
In case it may help, I'm using this configuration that works OK.
My gluetun container is named gluetunslskd as I've another gluetun container running on the same host for qBittorrent (so running two gluetuns, one for Soulseek, one for the torrents).

`compose.yaml`:
```yaml
services:
  gluetunslskd:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetunslskd
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 5030:5030 # slksd http
      - 5031:5031 # slskd https
    volumes:
      # XXX: we use the same data folder for gluetun and slskd so that glutun
      # can write to it
      - ./slskd/app:/app
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      VPN_SERVICE_PROVIDER: protonvpn
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${SLSKD_WIREGUARD_PRIVATE_KEY}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      PORT_FORWARD_ONLY: on
      VPN_PORT_FORWARDING: on
      WIREGUARD_ADDRESSES: 10.2.0.2/32
      UPDATER_PERIOD: 24h
      VPN_PORT_FORWARDING_UP_COMMAND: >
        '/bin/sh -c "sed -i 's/listen_port:.*/listen_port\: {{PORTS}}/' /app/slskd.yml"'

  slskd:
    image: slskd/slskd:0.23.2
    container_name: slskd
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      SLSKD_REMOTE_CONFIGURATION: true
    volumes:
      - ./slskd/app:/app
      - /mnt/media:/media
    user: 1000:1000
    network_mode: 'service:gluetunslskd'
    depends_on:
      gluetunslskd:
        condition: service_healthy
    restart: unless-stopped
```

`.env`:
```
SLSKD_WIREGUARD_PRIVATE_KEY=XXXXXXXXXXXXXXX
SERVER_COUNTRIES=France
```

**Comment by ovizii** [comment]
> In case it may help, I'm using this configuration that works OK. My gluetun container is named gluetunslskd as I've another gluetun container running on the same host for qBittorrent (so running two gluetuns, one for Soulseek, one for the torrents).


Thanks for sharing. It's almost exactly like my own config except I use OpenVPN instead of WireGuard. It might be an issue with my VPMN provider though.

**Comment by Fran314** [comment]
@gwarf Thank you for sharing your configuration. Does portforwarding work for you? I'm asking because after a while I noticed that in my configuration it doesn't work. The port results open and users seem able to find me, but when trying to download files I'm sharing they get a "Connection Closed" error, and I get a similar error in the logs on my side:
```
Failed to upload file music\[redacted:file] to user [redacted:user]: Transfer failed: Read error: Unable to read data from the transport connection: Connection reset by peer.
```

I've tried to use your configuration (adapted a bit) but I get the same error. Did you stumble into something simlar and/or are you able to verify that other users are able to connect to you and download files through your open port?

**Comment by gwarf** [comment]
Yes, I'm able to download and upload content, even if there may be errors with some specific users, but I assume it's due to other reasons.
Have you created a suitable configuration in ProtonVPN: https://account.proton.me/u/0/vpn/WireGuard ?
You need to enable NAT-PMP, but not Moderade NAT. I've also disabled the blocks and kept the VPN accelerator.

Did you uncomment the `listen_port` entry in the conf file? Do you see it being changed automatically?

In the slksd web UI, I've something like this for the `/app/skskd.yml`:
```yaml
soulseek:
  address: vps.slsknet.org
  port: 2271
  username: XXXXXXXXXXXXXXXX
  password: XXXXXXXXX
#   description: |
#     A slskd user. https://github.com/slskd/slskd
#   picture: path/to/slsk-profile-picture.jpg
#   listen_ip_address: 0.0.0.0
  listen_port: 64460
```

And the `listen_port` line is updated when the forwarded port changes.

**Comment by Fran314** [comment]
Yes, in fact the config file is exclusively

```yaml
soulseek:
  listen_port: 55129
```
because I set the other settings through environment variables. Also I can confirm that the port correctly updates and reflects the one I see in the gluetun logs. I can see this both in the config file that gets overwritten and in the options panel inside the slskd WebUI.

As for generating the configuration files, I do the following:
- select GNU/Linux as platform (maybe I should select Router? I don't think so but I haven't tried it)
- select "No filter" for the NetShield thing
- leave "Moderate NAT" UNSELECTED
- SELECT "NAT-PMP"
- let SELECTED "VPN Accelerator"

Then for the server choice, I have tried the following:
- using the "Use the best server according to current load and position" at the top
- using "Standard server configs" and manually selecting a server (I've tried from Switzerland and from France) making sure to select one that has the double arrow icon which if I'm not mistaken is for Portforwarding

I then copy the Private Key from the generated configuration and put it in the `.env` file. The rest of the configuration is as follows:

`compose.yaml`
```yaml
services:
  gluetun-slskd:
    image: qmcgaw/gluetun:v3.40.0
    container_name: gluetun-slskd
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      PUID: 1000
      PGID: 100
      VPN_SERVICE_PROVIDER: protonvpn
      # See https://github.com/qdm12/gluetun-wiki/tree/main/setup#setup
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${SLSKD_WIREGUARD_PRIVATE_KEY}
      # SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      PORT_FORWARD_ONLY: on
      VPN_PORT_FORWARDING: on
      WIREGUARD_ADDRESSES: 10.2.0.2/32
      UPDATER_PERIOD: 24h
      VPN_PORT_FORWARDING_UP_COMMAND: >
        '/bin/sh -c "sed -i 's/listen_port:.*/listen_port\: {{PORTS}}/' /app/slskd.yml"'

    ports:
      - 5030:5030
      - 5031:5031
    volumes:
      - ./app:/app
    restart: unless-stopped
  slskd:
    image: slskd/slskd:0.23.2
    container_name: slskd
    user: 1000:100
    environment:
      - PUID=1000
      - PGID=100
      - SLSKD_REMOTE_CONFIGURATION=true
      - SLSKD_SLSK_ADDRESS=server.slsknet.org
      - SLSKD_SLSK_PORT=2242
      - SLSKD_SLSK_USERNAME=${SLSKD_SLSK_USERNAME}
      - SLSKD_SLSK_PASSWORD=${SLSKD_SLSK_PASSWORD}
      - SLSKD_SHARED_DIR=/music
      - SLSKD_DOWNLOADS_DIR=/downloads
      - SLSKD_INCOMPLETE_DIR=/incompletes
      - SLSKD_NO_AUTH=true
    volumes:
      - /mnt/hdd1/slskd/music:/music:rw
      - /mnt/hdd1/slskd/downloads:/downloads:rw
      - /mnt/hdd1/slskd/incompletes:/incompletes:rw
      - ./app:/app
    network_mode: 'service:gluetun-slskd'
    depends_on:
      gluetun-slskd:
        condition: service_healthy
    restart: unless-stopped
```

Note:
- the `GID` being `100` is not a mistake, it's just that for some reason on NixOS that's the default user
- the `SERVER_COUNTRIES` is currently commented out but I've tried it with and without just to make sure that I wasn't creating issues with it

The `.env` has the following structure:
```
SLSKD_WIREGUARD_PRIVATE_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX=
# SERVER_COUNTRIES=Switzerland
SLSKD_SLSK_USERNAME=XXXXXXXXXXXXXX
SLSKD_SLSK_PASSWORD=XXXXXXXXXXXXXX
```

In all the different combinations of configurations I get the same `Connection reset by peer` error, which I'm assuming is a VPN/Wireguard issue

Am I doing something wrong in the configuration generation? How did you select the server for creating the configuration? I'm a bit lost.

Just to be 100% sure, the firewall of the host machine shouldn't be an issue, right? By default I have only some open ports (80, ...), and the the random port forwarded by gluetun is not open on the host machine. I don't think this should be an issue, but it's not clear to me what the `/dev/net/tun` device is doing and since gluetun is using the one from the host mahcine, maybe it has something to do with it? Just a shot in the dark dunno
