### ISSUE TITLE
Add download quotas

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#388]
#346 introduced slot and bandwidth limiting by group.  Expanding on that idea, file and overall size quotas should be added.

On a per-user basis, track the overall number of files and data downloaded, and prevent users from enqueuing more files if they have exceeded their configured quota for a given time period.  Include settings for daily and weekly limits to start, and consider monthly.

"daily" should be defined as the previous 24 hours, and "weekly" should be defined as the previous 7 days.

This feature depends on #387, as completed transfers need to be persisted so we can count them and aggregate their size.

**Comment by Octoputty** [comment]
I'm really enjoying this project but unfortunately my client is getting hammered with huge queues that I can't keep up with. This issue would really help and I believe it to be a necessary feature. I'm hoping it's added soon!

**Comment by jpdillingham** [comment]
This is available in the canary release that just went out, but I'm holding off on adding official documentation for it until I do some more testing.  The configuration looks like:

```yaml
groups:
  default:
    limits:
      queued:
        files: ~
        megabytes: ~
      daily:
        files: 33
        megabytes: 500
      weekly:
        files: ~
        megabytes: ~
```

Null values (`~`) mean no limits apply.  The default limits don't impact other user groups right now, but I'm considering adding "global" limits (similar to how speed limits work).

I'd encourage anyone that wants to test to create a new user group and opt a few people into at a time; if anything malfunctions people may wind up in your DMs.

Feedback appreciated greatly!
