### ISSUE TITLE
"slskd exited with code 132" in docker on raspberry pi 4

### ISSUE THREAD

**Issue by avephill** [slskd/slskd#411]
I'm pretty inexperienced with docker and I'm having a hell of a time getting slskd up and running on my raspberry pi 4

I'm using pretty much the default docker-compose.yaml just to see if I can get it up and running. it looks like this:
```
---
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5000:5000"
      - "5001:5001"
      - "50000:50000"
    volumes:
      - /var/slskd:/app
    restart: always
```

When I run `docker-compose up` I receive the following: 
```
Creating network "soulseek_default" with the default driver
Pulling slskd (slskd/slskd:)...
latest: Pulling from slskd/slskd
f98812e1a494: Pull complete
79eadc732d6b: Pull complete
2be1aba99176: Pull complete
f2b9f1cb14ce: Pull complete
4cbed2f46d39: Pull complete
9e904fb8165f: Pull complete
Digest: sha256:59ee4856c92ac79dd2299689a0dc6184d85fd22794cb335a68d3be31f7768b3c
Status: Downloaded newer image for slskd/slskd:latest
Creating slskd ... done
Attaching to slskd
slskd exited with code 132
```

Even if I create a `slskd.yml` in `/var/slskd` with `debug:true` I can't get anymore information about what is going wrong.

I'd appreciate any help.
