### ISSUE TITLE
Publish Docker images for 32 and 64 bit ARM

### ISSUE THREAD

**Issue by jpdillingham** [slskd/slskd#43]
Investigate [Docker Buildx](https://docs.docker.com/buildx/working-with-buildx/).

Incorporate this into the CI pipeline, potentially using [this action](https://github.com/marketplace/actions/docker-buildx).

**Comment by jpdillingham** [comment]
I was able to add arm64 support, but arm32 is blocked due to a lack of a suitable arm32 alpine runtime dependency image: https://github.com/dotnet/core/issues/5687

**Comment by kromsam** [comment]
I tried to use the arm64 release. This is the output I got:

`standard_init_linux.go:219: exec user process caused: exec format error`

So still the same output as before. I used this in my docker-compose file:

```
# VPN
  vpn:
    container_name: vpn
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    restart: always
    network_mode: bridge
    volumes:
      - ${APPDATA}/OpenVPN:/gluetun
    environment:
      - VPNSP=${VPNSP}
      - USER=${VPNUSER}
      - PASSWORD=${VPNPASS}
      - REGION=${VPNREGION}
      - PORT_FORWARDING=on
    ports:
      - 9091:9091 # Transmission
      - 5000:5000 # Soulseek
      - 5001:5001 # Soulseek
      - 9117:9117 # Jackett
      - 6767:6767 # Bazarr
      - 8686:8686 # Lidarr
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr

# Soulseek
  soulseek_web:
    container_name: soulseek_web
    image: slskd/slskd:latest
    restart: always
    depends_on:
      - vpn
    network_mode: "service:vpn"
    environment:
      - SLSKD_SLSK_USERNAME=${SLSK_USER}
      - SLSKD_SLSK_PASSWORD=${SLSK_PW}
    volumes:
      - ${APPDATA}/Soulseek:/root
      - ${DOWNLOADS}:/var/slskd/downloads
      - ${MEDIA}:/var/slskd/shared
```

I am using the RockPro64 SBC running Armbian.

```
uname -m
aarch64
```
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/8/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.3.0-6' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --disable-libphobos --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Debian 8.3.0-6) 
```

It seems as if the arm version is still picked. [On Docker Hub, the arm and the amd version seem to be practically identical as well](https://hub.docker.com/layers/slskd/slskd/latest/images/sha256-e2081379c31c0aac55a0baea25274e943c76327a33ce05e09ab353a1b5619dd7?context=explore), although I'm not sure if that's a problem.

Thanks for taking quick action though!

All the best,
