### ISSUE TITLE
Environment variables passed through Docker ignored

### ISSUE THREAD

**Issue by ramadan8** [slskd/slskd#456]
Just installed this using the following `docker-compose` configuration.

```yaml
# ...other services...

soulseek:
  image: slskd/slskd
  network_mode: service:gluetun
  volumes:
    - /srv/config/slskd:/app
    - /srv/data/hosted/soulseek:/hosted
  environment:
    - SLSK_USERNAME
    - SLSK_PASSWORD
    - SLSKD_SHARED_DIR=/hosted
  restart: unless-stopped

# ...other services...
```

I have a `.env` file in the same directory with my Soulseek username/password listed as variables like so.

```
SLSK_USERNAME=usernamehere
SLSK_PASSWORD=passwordhere
```

I start the program by running `docker-compose up -d`. It loads fine, but any values I specify as environment variables are ignored.

![Image showing the "Options" tab in the website's settings](https://i.imgur.com/Rkfyg5n.png)

If I save the files in `/app/slskd.yml` using the YAML format then it works fine, but I'd like to use it through environment variables to keep things centralised.

One thing to note is that the directory in `SLSKD_SHARED_DIR` is saved properly, and I can see the files from it even without setting it as shared in `/app/slskd.yml`.

Other than this small problem I'm really liking this project, great work :)
