### ISSUE TITLE
the prefixes - or ! to exclude the path from the shares make the path considered relative and therefore don't work

### ISSUE THREAD

**Issue by fluxtendu** [slskd/slskd#461]
Maybe there is another reason but even after many tests, I never managed to exclude a directory or a file. (No issue to share the directory)

slskd version: 0.15.4.0

slskd.yml:
```
directories:
  incomplete: '/mnt/Incoming/slskd/_incomplete/'
  downloads: '/mnt/Incoming/slskd/'
  shared:
    - '[Audiothèque]/mnt/Musique/Audiothèque/'
    - '!/mnt/Musique/Audiothèque/desktop.ini'
    - '!/mnt/Musique/Audiothèque/Playlists'
    - '!/mnt/Musique/Audiothèque/$RECYCLE.BIN'
```
error log:
`Invalid configuration: Directories: Share !/mnt/Musique/Audiothèque/desktop.ini contains a relative path; only absolute paths are supported. Share !/mnt/Musique/Audiothèque/Playlists contains a relative path; only absolute paths are supported. Share !/mnt/Musique/Audiothèque/$RECYCLE.BIN contains a relative path; only absolute paths are supported.`
