### ISSUE TITLE
update docker docs to include the --user and user: flags

### ISSUE THREAD

**Issue by davidzx** [slskd/slskd#473]
after an update i had to figure out again how to use the user flags so files are owned by the user and not root. a snippet in the docker docs would help

something like
For the files to be owned by the user and not root you can set the user flag

docker run
user pgid:uuid(1000:1000)
```
docker run -d \
  -p 5000:5000 \
  -p 5001:5001 \
  -p 50000:50000 \
  -v /var/slskd:/app \
  -v /home/JohnDoe/Music:/music \
  -v /home/JohnDoe/eBooks:/ebooks \
  -e "SLSKD_SHARED_DIR=/music;/ebooks" \
  --name slskd \
  --user 1000:1000
  slskd/slskd:latest
```

or yml
user: 1000:1000
```
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    user: 1000:1000
```
