### ISSUE TITLE
Missing search results compared to SoulseekQt

### ISSUE THREAD

**Issue by randrej** [slskd/slskd#529]
When running this tool and SoulseekQt from the same computer, with the same account and the same shared files, you get fewer search results. This is especially true for searches with few results (say, "Dark Dopamine Ceremony"), where slskd returns no results while SoulseekQt has a couple.

What gives?

Here's the config for slskd:

```yaml
debug: false
directories:
  downloads: /downloads/complete
  incomplete: /downloads/incomplete
  shared:
    - /music
feature:
  prometheus: false
  swagger: false
filters:
  share:
    - \.db$
global:
  download:
    slots: 30
    speedLimit: 10000
  upload:
    slots: 5
    speedLimit: 1000
groups:
  default:
    upload:
      priority: 1
      slots: 2147483647
      speedLimit: 2147483647
      strategy: roundrobin
  leechers:
    thresholds:
      directories: 1
      files: 1
    upload:
      priority: 1
      slots: 2147483647
      speedLimit: 2147483647
      strategy: roundrobin
  userDefined: {}
instanceName: default
integration:
  ftp:
    address: null
    connectionTimeout: 5000
    enabled: false
    encryptionMode: auto
    ignoreCertificateErrors: false
    overwriteExisting: true
    password: null
    port: 21
    remotePath: /
    retryAttempts: 3
    username: null
  pushbullet:
    accessToken: null
    cooldownTime: 900000
    enabled: false
    notificationPrefix: "From slskd:"
    notifyOnPrivateMessage: true
    notifyOnRoomMention: true
    retryAttempts: 3
logger:
  loki: null
noConnect: false
noLogo: false
noShareScan: false
noStart: false
noVersionCheck: false
remoteConfiguration: false
rooms: []
soulseek:
  connection:
    buffer:
      read: 1048576
      transfer: 4194304
      write: 1048576
      writeQueue: 1000
    proxy:
      address: null
      enabled: false
      password: null
      port: null
      username: null
    timeout:
      connect: 30000
      inactivity: 30000
  description: ""
  diagnosticLevel: Info
  distributedNetwork:
    childLimit: 10000
    disableChildren: false
    disabled: false
    logging: true
  listenPort: 50000
  password: "*****"
  username: redacted
web:
  authentication:
    disabled: false
    jwt:
      key: "*****"
      ttl: 604800000
    password: "*****"
    username: redacted
  contentPath: wwwroot
  https:
    certificate:
      password: null
      pfx: null
    disabled: true
    force: false
    port: 5001
  logging: false
  port: 5000
  urlBase: /
```

It also seems like I'm uploading a lot less (getting fewer upload requests), but this may be subjective.
