### ISSUE TITLE
ENHANCEMENT Review Docker CPU

### ISSUE THREAD

**Issue by ldexterldesign** [slskd/slskd#552]
👋

Thanks for wonderful software

Hope y'all good

I'm discontent with (Docker) CPU usage

I'm more discontent with my laptop being a radiator so trying to find out what may be causing it. I did stop my slskd container and it did seem to reduce the heat a little but I could have been imagining it (lot of variables).

Is 5% CPU (idle) normal?:
* If yes then how may I reduce it and - if it's of wider concern - then how may we reduce it
* If no then what could be causing this

Screenshot:
<img width="1792" alt="Screenshot 2022-07-19 at 23 29 52" src="https://user-images.githubusercontent.com/1715809/179866258-5aa4bfc5-97ff-4cfa-8ee1-a971a9480890.png">

# Log

Unsure if it's relevant, ask and I'll add something

If you're reading and:
- agree then please vote up (e.g. +1, like), or;
- disagree then please vote down (e.g. -1, dislike) - I'd love to know why?

Welcome feedback/input

If you have any issues (e.g. questions/queries) then happy to help

Hope to hear back

Cheers

Hardware: Apple, MacBook Pro (16-inch, 2019)]
Software - OS: Apple, macOS, 12.4 (21F79)
Software - application: image ID f36fc21fdd0b ???

```docker
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5000:5000"
      - "5001:5001"
      - "50000:50000"
    volumes:
      - ~/Downloads/-data/-config/slskd:/app
      - ~/Downloads/-data/slskd/complete:/complete
      - ~/Downloads/-data/slskd/incomplete:/incomplete
      - ~/Downloads/-data/jellyfin/apple/audio:/share
    restart: unless-stopped
    environment:
      - SLSKD_DOWNLOADS_DIR=/complete
      - SLSKD_INCOMPLETE_DIR=/incomplete
      - SLSKD_SHARED_DIR=/share
      - SLSKD_SLSK_USERNAME=anon
      - SLSKD_SLSK_PASSWORD=anon
      - SLSKD_USERNAME=anon
      - SLSKD_PASSWORD=anon
```

```yaml
➜  ~ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.8.2)
  compose: Docker Compose (Docker Inc., v2.6.0)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 12
  Running: 11
  Paused: 0
  Stopped: 1
 Images: 23
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 212e8b6fa2f44b9c21b2798135fc6fb7c53efc16
 runc version: v1.1.1-0-g52de29d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.104-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 7.676GiB
 Name: docker-desktop
 ID: UR5V:VZ74:OARZ:CEY4:D3UW:BTQA:4WEU:7YCF:25CT:ITTX:KGJE:ZGSD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false
```
