### ISSUE TITLE
No search results using docker - network issue? Ports are open

### ISSUE THREAD

**Issue by mminklet** [slskd/slskd#897]
Hi, set up slskd on a rpi3 with docker. I am logged in and connected to the network, but cannot get any results. No filters, using obvious searches. I can't browse a user, tho I can search for them, see some basic details (but 'No User Info') and search for chat rooms. I suspect it's due to ports but they are open

I've got a static IP (and soulseek works fine on my mac). I've forwarded the listening port on docker-proxy (50300) and tested it online, it's open to the public.

`tcp        0      0 0.0.0.0:50300           0.0.0.0:*               LISTEN      91794/docker-proxy`

Is there anything else that needs to be done? I have shared a folder, tho there's nothing in it yet

I enabled debug mode but it's not showing me anything in the logs.

This is my info config

```
version:
  full: 0.17.5.0 (0.17.5.0+ea52f17d)
  current: 0.17.5.0
  latest: 0.17.5.0
  isUpdateAvailable: false
  isCanary: false
  isDevelopment: false
pendingReconnect: false
pendingRestart: false
server:
  address: vps.slsknet.org
  ipEndPoint: 208.76.170.59:2271
  state: Connected, LoggedIn
  isConnected: true
  isLoggedIn: true
  isTransitioning: false
relay:
  mode: Controller
  controller:
    address: null
    state: Disconnected
  agents: []
user:
  username: foobar <- not real
  privileges:
    isPrivileged: true
    privilegesRemaining: 1772850
  statistics:
    averageSpeed: 0
    directoryCount: 0
    fileCount: 0
    uploadCount: 0
distributedNetwork:
  branchLevel: 4
  branchRoot: indadb
  canAcceptChildren: true
  childLimit: 25
  children: []
  hasParent: true
  isBranchRoot: false
  parent: Andres17
shares:
  scanPending: false
  scanning: false
  ready: true
  faulted: false
  cancelled: false
  scanProgress: 1
  hosts:
    - local
  directories: 0
  files: 0
rooms: []
users:
  - username: null
    group: null
    statistics:
      averageSpeed: 0
      directoryCount: 0
      fileCount: 0
      uploadCount: 0
    status: null
```
