### ISSUE TITLE
slskd will not find directories that are in the docker compose file

### ISSUE THREAD

**Issue by halpz** [slskd/slskd#929]
```
---
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - /srv/dev-disk-by-uuid-27d23c0a-5186-4bba-a7bc-71076e3bb75a/apps/slskd:/app
      - /srv/dev-disk-by-uuid-27d23c0a-5186-4bba-a7bc-71076e3bb75a/music:/music
    restart: always
```

I have put a music folder with the label 'music'. but i cannot specify this in the yaml file. it errors saying it doesn't exist:

```
# directories:
#   incomplete: "/music/incomplete"
#   downloads: "/music"
```

how can I get this to work?
