### ISSUE TITLE
implement alternate rate limits

### ISSUE THREAD

**Issue by paulo-erichsen** [slskd/slskd#985]
my ISP only offers a crappy upload speed. I'd like to see if it were possible to implement an "Alternate Rate Limit" depending on user configured schedule.

Example: qbittorrent offers this

![image](https://github.com/slskd/slskd/assets/6787502/902986f5-083b-4f92-9307-8c10b97ed7e5)

For instance: I'd like to set a schedule to upload/download with max speed during the night when nobody is awake, but then limit the speed during the day

Right now, there's only one global setting for rates

```yaml
global:
  upload:
    slots: 20
    speed_limit: 1000
  download:
    slots: 500
    speed_limit: 1000
```
